version: "4"

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    networks:
      - book-net
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
      - php

  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    networks:
      - book-net
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"

  composer:
    build:
      context: ./docker
      dockerfile: composer.dockerfile
    networks:
      - book-net
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  npm:
    image: node:current-alpine
    volumes:
      - ./:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    networks:
      - book-net
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  console:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    networks:
      - book-net
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - database
    entrypoint: ["php", "/var/www/html/bin/console"]

volumes:
  database_data:

networks:
  book-net:
    driver: bridge
